In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [19]:
df = pd.read_csv(r'C:\Users\Nita\Desktop\ProjectsPersonal\Ranking/movies_data.csv')
df.head()

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,Toy Story,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",10/30/1995,81.0,Released,Toy Story,7.7,5415.0
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,Jumanji,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",12/15/1995,104.0,Released,Jumanji,6.9,2413.0
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,Grumpier Old Men,11.712900,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",12/22/1995,101.0,Released,Grumpier Old Men,6.5,92.0
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,Waiting to Exhale,3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,12/22/1995,127.0,Released,Waiting to Exhale,6.1,34.0
4,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Father of the Bride Part II,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...",2/10/1995,106.0,Released,Father of the Bride Part II,5.7,173.0

### Popularity-Based Ranking:

In [18]:
top_20_popularity = df.sort_values(by='popularity', ascending=False).head(20)
top_20_popularity

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count
30543,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",211672,en,Minions,547.488298,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",6/17/2015,91.0,Released,Minions,6.4,4729.0
33159,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",297762,en,Wonder Woman,294.337037,"[{'name': 'Dune Entertainment', 'id': 444}, {'...",5/30/2017,141.0,Released,Wonder Woman,7.2,5025.0
41885,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,en,Beauty and the Beast,287.253654,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",3/16/2017,129.0,Released,Beauty and the Beast,6.8,5530.0
43277,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",339403,en,Baby Driver,228.032744,"[{'name': 'Big Talk Productions', 'id': 443}, ...",6/28/2017,113.0,Released,Baby Driver,7.2,2083.0
24349,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",177572,en,Big Hero 6,213.849907,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",10/24/2014,102.0,Released,Big Hero 6,7.8,6289.0
26446,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",293660,en,Deadpool,187.860492,[{'name': 'Twentieth Century Fox Film Corporat...,2/9/2016,108.0,Released,Deadpool,7.4,11444.0
26448,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,en,Guardians of the Galaxy Vol. 2,185.330992,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",4/19/2017,137.0,Released,Guardians of the Galaxy Vol. 2,7.6,4858.0
14527,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",19995,en,Avatar,185.070892,"[{'name': 'Ingenious Film Partners', 'id': 289...",12/10/2009,162.0,Released,Avatar,7.2,12114.0
24245,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",245891,en,John Wick,183.870374,"[{'name': 'Summit Entertainment', 'id': 491}, ...",10/22/2014,101.0,Released,John Wick,7.0,5499.0
23576,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, '...",210577,en,Gone Girl,154.801009,[{'name': 'Twentieth Century Fox Film Corporat...,10/1/2014,145.0,Released,Gone Girl,7.9,6023.0
24766,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",131631,en,The Hunger Games: Mockingjay - Part 1,147.098006,"[{'name': 'Lionsgate', 'id': 1632}, {'name': '...",11/18/2014,123.0,Released,The Hunger Games: Mockingjay - Part 1,6.6,5767.0
43888,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",281338,en,War for the Planet of the Apes,146.161786,"[{'name': 'Chernin Entertainment', 'id': 7076}]",7/11/2017,140.0,Released,War for the Planet of the Apes,6.7,1675.0
26449,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",271110,en,Captain America: Civil War,145.882135,"[{'name': 'Studio Babelsberg', 'id': 264}, {'n...",4/27/2016,147.0,Released,Captain America: Civil War,7.1,7462.0
291,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",680,en,Pulp Fiction,140.950236,"[{'name': 'Miramax Films', 'id': 14}, {'name':...",9/10/1994,154.0,Released,Pulp Fiction,8.3,8670.0
26442,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,en,Pirates of the Caribbean: Dead Men Tell No Tales,133.827820,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",5/23/2017,129.0,Released,Pirates of the Caribbean: Dead Men Tell No Tales,6.6,2814.0
12463,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",155,en,The Dark Knight,123.167259,"[{'name': 'DC Comics', 'id': 429}, {'name': 'L...",7/16/2008,152.0,Released,The Dark Knight,8.3,12269.0
535,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",78,en,Blade Runner,96.272374,"[{'name': 'Shaw Brothers', 'id': 5798}, {'name...",6/25/1982,117.0,Released,Blade Runner,7.9,3833.0
17776,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,en,The Avengers,89.887648,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",4/25/2012,143.0,Released,The Avengers,7.4,12000.0
42932,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",268531,en,Captain Underpants: The First Epic Movie,88.561239,"[{'name': 'DreamWorks Animation', 'id': 521}, ...",6/1/2017,89.0,Released,Captain Underpants: The First Epic Movie,6.5,159.0
33163,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",339988,en,The Circle,88.439243,"[{'name': 'Likely Story', 'id': 1785}, {'name'...",4/27/2017,110.0,Released,The Circle,5.4,1015.0

### Vote Count-Based Ranking:

In [20]:
top_20_vote_count = df.sort_values(by='vote_count', ascending=False).head(20)
top_20_vote_count

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count
15451,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",27205,en,Inception,29.108149,"[{'name': 'Legendary Pictures', 'id': 923}, {'...",7/14/2010,148.0,Released,Inception,8.1,14075.0
12463,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",155,en,The Dark Knight,123.167259,"[{'name': 'DC Comics', 'id': 429}, {'name': 'L...",7/16/2008,152.0,Released,The Dark Knight,8.3,12269.0
14527,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",19995,en,Avatar,185.070892,"[{'name': 'Ingenious Film Partners', 'id': 289...",12/10/2009,162.0,Released,Avatar,7.2,12114.0
17776,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,en,The Avengers,89.887648,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",4/25/2012,143.0,Released,The Avengers,7.4,12000.0
26446,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",293660,en,Deadpool,187.860492,[{'name': 'Twentieth Century Fox Film Corporat...,2/9/2016,108.0,Released,Deadpool,7.4,11444.0
22787,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",157336,en,Interstellar,32.213481,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",11/5/2014,169.0,Released,Interstellar,8.1,11187.0
19990,"[{'id': 18, 'name': 'Drama'}, {'id': 37, 'name...",68718,en,Django Unchained,19.785025,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...",12/25/2012,165.0,Released,Django Unchained,7.8,10297.0
23653,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",118340,en,Guardians of the Galaxy,53.291601,"[{'name': 'Marvel Studios', 'id': 420}, {'name...",7/30/2014,121.0,Released,Guardians of the Galaxy,7.9,10014.0
2832,"[{'id': 18, 'name': 'Drama'}]",550,en,Fight Club,63.869599,[{'name': 'Twentieth Century Fox Film Corporat...,10/15/1999,139.0,Released,Fight Club,8.3,9678.0
18199,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",70160,en,The Hunger Games,20.031667,"[{'name': 'Lionsgate', 'id': 1632}, {'name': '...",3/12/2012,142.0,Released,The Hunger Games,6.9,9634.0
26435,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",76341,en,Mad Max: Fury Road,29.361780,"[{'name': 'Village Roadshow Pictures', 'id': 7...",5/13/2015,120.0,Released,Mad Max: Fury Road,7.3,9629.0
18207,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",49026,en,The Dark Knight Rises,20.582580,"[{'name': 'Legendary Pictures', 'id': 923}, {'...",7/16/2012,165.0,Released,The Dark Knight Rises,7.6,9263.0
2447,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",603,en,The Matrix,33.366332,"[{'name': 'Village Roadshow Pictures', 'id': 7...",3/30/1999,136.0,Released,The Matrix,7.9,9079.0
12570,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",1726,en,Iron Man,22.073099,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",4/30/2008,126.0,Released,Iron Man,7.4,8951.0
20758,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",68721,en,Iron Man 3,23.721243,"[{'name': 'Marvel Studios', 'id': 420}]",4/18/2013,130.0,Released,Iron Man 3,6.8,8951.0
4849,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",120,en,The Lord of the Rings: The Fellowship of the Ring,32.070725,"[{'name': 'WingNut Films', 'id': 11}, {'name':...",12/18/2001,178.0,Released,The Lord of the Rings: The Fellowship of the Ring,8.0,8892.0
24977,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",135397,en,Jurassic World,32.790475,"[{'name': 'Universal Studios', 'id': 13}, {'na...",6/9/2015,124.0,Released,Jurassic World,6.5,8842.0
291,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",680,en,Pulp Fiction,140.950236,"[{'name': 'Miramax Films', 'id': 14}, {'name':...",9/10/1994,154.0,Released,Pulp Fiction,8.3,8670.0
19910,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",49051,en,The Hobbit: An Unexpected Journey,23.253089,"[{'name': 'WingNut Films', 'id': 11}, {'name':...",11/26/2012,169.0,Released,The Hobbit: An Unexpected Journey,7.0,8427.0
313,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",278,en,The Shawshank Redemption,51.645403,"[{'name': 'Castle Rock Entertainment', 'id': 9...",9/23/1994,142.0,Released,The Shawshank Redemption,8.5,8358.0

### Vote Average-Based Ranking:

In [21]:
top_20_vote_average = df.sort_values(by='vote_average', ascending=False).head(20)
top_20_vote_average

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count
21837,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",293412,en,Running Wild,0.465559,[],1/1/1995,0.0,Released,Running Wild,10.0,1.0
37322,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",131907,es,No somos nadie,0.167703,[],1/1/2002,91.0,Released,God is on Air,10.0,1.0
37137,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",254902,uk,Лісова пісня. Мавка,0.239236,"[{'name': 'Dovzhenko Film Studios', 'id': 4581}]",7/23/1980,83.0,Released,A Story of the Forest: Mavka,10.0,2.0
11367,"[{'id': 10402, 'name': 'Music'}, {'id': 99, 'n...",68736,en,Joe Cocker - Mad Dogs & Englishmen,0.035284,"[{'name': 'A&M Films', 'id': 11043}, {'name': ...",8/27/1971,117.0,Released,Joe Cocker - Mad Dogs & Englishmen,10.0,1.0
37166,"[{'id': 18, 'name': 'Drama'}]",382899,sl,Mama,0.066061,"[{'name': 'Transmedia', 'id': 19917}, {'name':...",1/27/2016,90.0,Released,Mother,10.0,1.0
27446,"[{'id': 16, 'name': 'Animation'}]",53543,en,Claymation Comedy of Horrors,0.007319,[],5/29/1991,30.0,Released,Claymation Comedy of Horrors,10.0,1.0
21969,[],143534,en,The White Shadow,0.143297,[],5/5/1924,44.0,Released,The White Shadow,10.0,1.0
37283,[],162611,en,Portrait of a Young Man in Three Movements,0.036471,[],4/15/1931,54.0,Released,Portrait of a Young Man in Three Movements,10.0,1.0
37342,[],65270,en,Kenny Chesney: Summer In 3D,0.071225,[],8/21/2010,0.0,Rumored,Kenny Chesney: Summer In 3D,10.0,1.0
37082,[],260352,en,Book of Days,0.041070,[],11/30/1989,74.0,Released,Book of Days,10.0,1.0
11032,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",43147,en,Blessed Event,0.090803,"[{'name': 'Warner Bros.', 'id': 6194}]",9/10/1932,80.0,Released,Blessed Event,10.0,1.0
37408,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",47683,el,Αγάπη στα 16,0.041196,[],11/25/2004,102.0,Released,Love at 16,10.0,1.0
37610,"[{'id': 35, 'name': 'Comedy'}]",185273,en,Bowery Battalion,0.462816,"[{'name': 'Monogram Pictures', 'id': 4395}]",1/24/1951,69.0,Released,Bowery Battalion,10.0,1.0
37794,"[{'id': 18, 'name': 'Drama'}]",230284,en,One Man's Journey,0.625556,"[{'name': 'RKO Radio Pictures', 'id': 6}]",8/31/1933,72.0,Released,One Man's Journey,10.0,1.0
10439,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",34662,en,Li'l Abner,0.611118,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",12/11/1959,114.0,Released,Li'l Abner,10.0,1.0
27286,"[{'id': 18, 'name': 'Drama'}]",279979,en,The Court-Martial of Jackie Robinson,0.081817,"[{'name': 'Turner Pictures', 'id': 1765}, {'na...",10/15/1990,100.0,Released,The Court-Martial of Jackie Robinson,10.0,1.0
27508,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",180954,en,Vessel of Wrath,0.657391,"[{'name': 'Mayflower Pictures Corporation', 'i...",3/4/1938,92.0,Released,Vessel of Wrath,10.0,1.0
37077,"[{'id': 10752, 'name': 'War'}, {'id': 18, 'nam...",49099,da,Befrielsesbilleder,0.380644,"[{'name': 'Danmarks Radio (DR)', 'id': 119}, {...",6/30/1982,57.0,Released,Images of a Relief,10.0,1.0
25574,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",153936,en,Back to School with Franklin,0.040437,[],8/19/2003,47.0,Released,Back to School with Franklin,10.0,1.0
12146,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",42173,en,Chilly Scenes of Winter,0.009192,"[{'name': 'United Artists', 'id': 60}, {'name'...",10/19/1979,92.0,Released,Chilly Scenes of Winter,10.0,1.0

### Hybrid (Popularity and Vote Average) Ranking:

In [22]:
df['popularity_vote_avg'] = df['popularity'] * df['vote_average']
top_20_hybrid = df.sort_values(by='popularity_vote_avg', ascending=False).head(20)
top_20_hybrid

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count,popularity_vote_avg
30543,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",211672,en,Minions,547.488298,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",6/17/2015,91.0,Released,Minions,6.4,4729.0,3503.925107
33159,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",297762,en,Wonder Woman,294.337037,"[{'name': 'Dune Entertainment', 'id': 444}, {'...",5/30/2017,141.0,Released,Wonder Woman,7.2,5025.0,2119.226666
41885,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,en,Beauty and the Beast,287.253654,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",3/16/2017,129.0,Released,Beauty and the Beast,6.8,5530.0,1953.324847
24349,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",177572,en,Big Hero 6,213.849907,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",10/24/2014,102.0,Released,Big Hero 6,7.8,6289.0,1668.029275
43277,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",339403,en,Baby Driver,228.032744,"[{'name': 'Big Talk Productions', 'id': 443}, ...",6/28/2017,113.0,Released,Baby Driver,7.2,2083.0,1641.835757
26448,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,en,Guardians of the Galaxy Vol. 2,185.330992,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",4/19/2017,137.0,Released,Guardians of the Galaxy Vol. 2,7.6,4858.0,1408.515539
26446,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",293660,en,Deadpool,187.860492,[{'name': 'Twentieth Century Fox Film Corporat...,2/9/2016,108.0,Released,Deadpool,7.4,11444.0,1390.167641
14527,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",19995,en,Avatar,185.070892,"[{'name': 'Ingenious Film Partners', 'id': 289...",12/10/2009,162.0,Released,Avatar,7.2,12114.0,1332.510422
24245,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",245891,en,John Wick,183.870374,"[{'name': 'Summit Entertainment', 'id': 491}, ...",10/22/2014,101.0,Released,John Wick,7.0,5499.0,1287.092618
23576,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, '...",210577,en,Gone Girl,154.801009,[{'name': 'Twentieth Century Fox Film Corporat...,10/1/2014,145.0,Released,Gone Girl,7.9,6023.0,1222.927971
291,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",680,en,Pulp Fiction,140.950236,"[{'name': 'Miramax Films', 'id': 14}, {'name':...",9/10/1994,154.0,Released,Pulp Fiction,8.3,8670.0,1169.886959
26449,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",271110,en,Captain America: Civil War,145.882135,"[{'name': 'Studio Babelsberg', 'id': 264}, {'n...",4/27/2016,147.0,Released,Captain America: Civil War,7.1,7462.0,1035.763158
12463,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",155,en,The Dark Knight,123.167259,"[{'name': 'DC Comics', 'id': 429}, {'name': 'L...",7/16/2008,152.0,Released,The Dark Knight,8.3,12269.0,1022.288250
43888,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",281338,en,War for the Planet of the Apes,146.161786,"[{'name': 'Chernin Entertainment', 'id': 7076}]",7/11/2017,140.0,Released,War for the Planet of the Apes,6.7,1675.0,979.283966
24766,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",131631,en,The Hunger Games: Mockingjay - Part 1,147.098006,"[{'name': 'Lionsgate', 'id': 1632}, {'name': '...",11/18/2014,123.0,Released,The Hunger Games: Mockingjay - Part 1,6.6,5767.0,970.846840
26442,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,en,Pirates of the Caribbean: Dead Men Tell No Tales,133.827820,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",5/23/2017,129.0,Released,Pirates of the Caribbean: Dead Men Tell No Tales,6.6,2814.0,883.263612
535,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",78,en,Blade Runner,96.272374,"[{'name': 'Shaw Brothers', 'id': 5798}, {'name...",6/25/1982,117.0,Released,Blade Runner,7.9,3833.0,760.551755
17776,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,en,The Avengers,89.887648,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",4/25/2012,143.0,Released,The Avengers,7.4,12000.0,665.168595
42932,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",268531,en,Captain Underpants: The First Epic Movie,88.561239,"[{'name': 'DreamWorks Animation', 'id': 521}, ...",6/1/2017,89.0,Released,Captain Underpants: The First Epic Movie,6.5,159.0,575.648054
23592,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",119450,en,Dawn of the Planet of the Apes,75.385211,"[{'name': 'Ingenious Media', 'id': 290}, {'nam...",6/26/2014,130.0,Released,Dawn of the Planet of the Apes,7.3,4511.0,550.312040

### Weighted Rating:

In [23]:
C = df['vote_average'].mean()
m = df['vote_count'].quantile(0.90)
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)
df['weighted_rating'] = df.apply(weighted_rating, axis=1)
top_20_weighted = df.sort_values(by='weighted_rating', ascending=False).head(20)
top_20_weighted

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count,popularity_vote_avg,weighted_rating
313,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",278,en,The Shawshank Redemption,51.645403,"[{'name': 'Castle Rock Entertainment', 'id': 9...",9/23/1994,142.0,Released,The Shawshank Redemption,8.5,8358.0,438.985926,8.445575
826,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",238,en,The Godfather,41.109264,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",3/14/1972,175.0,Released,The Godfather,8.5,6024.0,349.428744,8.425040
10292,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",19404,hi,Dilwale Dulhania Le Jayenge,34.457024,"[{'name': 'Yash Raj Films', 'id': 1569}]",10/20/1995,190.0,Released,Dilwale Dulhania Le Jayenge,9.1,661.0,313.558918,8.418468
12463,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",155,en,The Dark Knight,123.167259,"[{'name': 'DC Comics', 'id': 429}, {'name': 'L...",7/16/2008,152.0,Released,The Dark Knight,8.3,12269.0,1022.288250,8.265304
2832,"[{'id': 18, 'name': 'Drama'}]",550,en,Fight Club,63.869599,[{'name': 'Twentieth Century Fox Film Corporat...,10/15/1999,139.0,Released,Fight Club,8.3,9678.0,530.117672,8.256169
291,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",680,en,Pulp Fiction,140.950236,"[{'name': 'Miramax Films', 'id': 14}, {'name':...",9/10/1994,154.0,Released,Pulp Fiction,8.3,8670.0,1169.886959,8.251166
521,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",424,en,Schindler's List,41.725123,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",11/29/1993,195.0,Released,Schindler's List,8.3,4436.0,346.318521,8.206198
23574,"[{'id': 18, 'name': 'Drama'}]",244786,en,Whiplash,64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...",10/10/2014,105.0,Released,Whiplash,8.3,4376.0,533.689917,8.204958
5467,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",129,ja,千と千尋の神隠し,41.048867,"[{'name': 'Studio Ghibli', 'id': 10342}]",7/20/2001,125.0,Released,Spirited Away,8.3,3968.0,340.705596,8.195569
2200,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",637,it,La vita è bella,39.394970,"[{'name': 'Miramax Films', 'id': 14}, {'name':...",12/20/1997,116.0,Released,Life Is Beautiful,8.3,3643.0,326.978251,8.186649
1169,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",240,en,The Godfather: Part II,36.629307,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",12/20/1974,200.0,Released,The Godfather: Part II,8.3,3418.0,304.023248,8.179525
1143,"[{'id': 18, 'name': 'Drama'}]",510,en,One Flew Over the Cuckoo's Nest,35.529554,"[{'name': 'United Artists', 'id': 60}, {'name'...",11/18/1975,133.0,Released,One Flew Over the Cuckoo's Nest,8.3,3001.0,294.895298,8.163642
350,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",13,en,Forrest Gump,48.307194,"[{'name': 'Paramount Pictures', 'id': 4}]",7/6/1994,142.0,Released,Forrest Gump,8.2,8147.0,396.118991,8.150042
1145,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",1891,en,The Empire Strikes Back,19.470959,"[{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twe...",5/17/1980,124.0,Released,The Empire Strikes Back,8.2,5998.0,159.661864,8.132613
1167,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",539,en,Psycho,36.826309,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",6/16/1960,109.0,Released,Psycho,8.3,2405.0,305.658365,8.131982
18419,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",77338,fr,Intouchables,16.086919,"[{'name': 'Gaumont', 'id': 9}, {'name': 'TF1 F...",11/2/2011,112.0,Released,The Intouchables,8.2,5410.0,131.912736,8.125502
39955,"[{'id': 10749, 'name': 'Romance'}, {'id': 16, ...",372058,ja,君の名は。,34.461252,"[{'name': 'CoMix Wave Films', 'id': 10198}]",8/26/2016,106.0,Released,Your Name.,8.5,1030.0,292.920642,8.110989
288,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",101,fr,Léon,20.477329,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...",9/14/1994,110.0,Released,Leon: The Professional,8.2,4293.0,167.914098,8.106824
3019,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",497,en,The Green Mile,19.966780,"[{'name': 'Castle Rock Entertainment', 'id': 9...",12/10/1999,189.0,Released,The Green Mile,8.2,4166.0,163.727596,8.104089
1161,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",769,en,GoodFellas,15.424092,"[{'name': 'Winkler Films', 'id': 8880}]",9/12/1990,145.0,Released,GoodFellas,8.2,3211.0,126.477554,8.076934

### Recent Releases (Latest Movies) Ranking:

In [24]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
top_20_recent = df.sort_values(by='release_date', ascending=False).head(20)
top_20_recent

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count,popularity_vote_avg,weighted_rating
26441,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",76600,en,Avatar 2,6.020055,[{'name': 'Twentieth Century Fox Film Corporat...,2020-12-16,0.0,In Production,Avatar 2,0.0,58.0,0.000000,4.151359
38611,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",299782,en,The Other Side of the Wind,0.238154,"[{'name': ""Les Films de l'Astrophore"", 'id': 7...",2018-12-31,0.0,Post Production,The Other Side of the Wind,0.0,1.0,0.000000,5.603062
30247,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",38700,en,Bad Boys for Life,2.178546,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...",2018-11-07,0.0,Planned,Bad Boys for Life,0.0,12.0,0.000000,5.248845
37862,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",332283,en,Mary Shelley,3.328261,"[{'name': 'Parallel Films', 'id': 5122}, {'nam...",2018-04-25,0.0,Post Production,Mary Shelley,0.0,1.0,0.000000,5.603062
44143,"[{'id': 18, 'name': 'Drama'}]",412059,en,Mobile Homes,0.155147,[],2018-04-04,105.0,Post Production,Mobile Homes,0.0,1.0,0.000000,5.603062
33161,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",302349,en,Iron Sky: The Coming Race,1.917649,"[{'name': '27 Films Production', 'id': 9282}, ...",2018-03-01,0.0,Post Production,Iron Sky: The Coming Race,0.0,0.0,0.000000,5.637648
33160,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",252983,en,Sly Cooper,1.531827,"[{'name': 'Rainmaker Entertainment', 'id': 221...",2017-12-31,0.0,In Production,Sly Cooper,0.0,0.0,0.000000,5.637648
30380,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,en,The King's Daughter,1.138419,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",2017-12-30,0.0,Post Production,The King's Daughter,0.0,4.0,0.000000,5.501802
43914,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",341689,en,How to Talk to Girls at Parties,2.068008,"[{'name': 'HanWay Films', 'id': 2395}, {'name'...",2017-12-27,102.0,Released,How to Talk to Girls at Parties,0.0,10.0,0.000000,5.309878
33172,"[{'id': 35, 'name': 'Comedy'}]",353616,en,Pitch Perfect 3,3.782498,[],2017-12-21,0.0,In Production,Pitch Perfect 3,0.0,3.0,0.000000,5.535146
41926,"[{'id': 99, 'name': 'Documentary'}]",433086,hi,Machines,0.469489,[],2017-11-30,71.0,Released,Machines,0.0,0.0,0.000000,5.637648
44142,[],413992,en,Sweet Virginia,1.718775,[],2017-11-17,95.0,Released,Sweet Virginia,0.0,1.0,0.000000,5.603062
26443,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,en,Justice League,25.944629,"[{'name': 'DC Comics', 'id': 429}, {'name': 'K...",2017-11-15,0.0,Post Production,Justice League,0.0,0.0,0.000000,5.637648
44601,"[{'id': 99, 'name': 'Documentary'}]",359749,en,78/52,2.488539,"[{'name': 'Exhibit A Pictures', 'id': 63267}]",2017-11-03,91.0,Released,78/52,0.0,4.0,0.000000,5.501802
41931,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",398818,en,Call Me by Your Name,4.300874,"[{'name': 'Sony Pictures Classics', 'id': 58},...",2017-10-27,130.0,Released,Call Me by Your Name,0.0,18.0,0.000000,5.073884
26447,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,en,Thor: Ragnarok,57.283628,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2017-10-25,0.0,Post Production,Thor: Ragnarok,0.0,0.0,0.000000,5.637648
43037,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",271404,en,Beyond Skyline,6.416249,"[{'name': 'Hydraulx', 'id': 10936}, {'name': '...",2017-10-20,0.0,Post Production,Beyond Skyline,0.0,30.0,0.000000,4.756766
44473,"[{'id': 99, 'name': 'Documentary'}]",432607,en,Dina,2.936666,[],2017-10-20,101.0,Post Production,Dina,0.0,2.0,0.000000,5.568897
44359,"[{'id': 99, 'name': 'Documentary'}]",439502,en,Resurrecting Hassan,1.319057,"[{'name': 'Handshake Productions', 'id': 86169}]",2017-09-22,100.0,Released,Resurrecting Hassan,0.0,0.0,0.000000,5.637648
38335,"[{'id': 27, 'name': 'Horror'}]",300665,en,Leatherface,9.742082,"[{'name': 'Campbell Grobman Films', 'id': 4873...",2017-09-14,90.0,Released,Leatherface,5.7,62.0,55.529867,5.654906

### Genre-Specific Ranking (e.g., Comedy):

In [25]:
comedy_movies = df[df['genres'].apply(lambda x: 'Comedy' in str(x))]
top_20_comedy = comedy_movies.sort_values(by='popularity', ascending=False).head(20)
top_20_comedy

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count,popularity_vote_avg,weighted_rating
30543,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",211672,en,Minions,547.488298,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",2015-06-17,91.0,Released,Minions,6.4,4729.0,3503.925107,6.374749
24349,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",177572,en,Big Hero 6,213.849907,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2014-10-24,102.0,Released,Big Hero 6,7.8,6289.0,1668.029275,7.745698
26446,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",293660,en,Deadpool,187.860492,[{'name': 'Twentieth Century Fox Film Corporat...,2016-02-09,108.0,Released,Deadpool,7.4,11444.0,1390.167641,7.375401
26448,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,en,Guardians of the Galaxy Vol. 2,185.330992,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2017-04-19,137.0,Released,Guardians of the Galaxy Vol. 2,7.6,4858.0,1408.515539,7.536673
26442,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,en,Pirates of the Caribbean: Dead Men Tell No Tales,133.827820,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2017-05-23,129.0,Released,Pirates of the Caribbean: Dead Men Tell No Tales,6.6,2814.0,883.263612,6.547614
42932,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",268531,en,Captain Underpants: The First Epic Movie,88.561239,"[{'name': 'DreamWorks Animation', 'id': 521}, ...",2017-06-01,89.0,Released,Captain Underpants: The First Epic Movie,6.5,159.0,575.648054,6.064795
350,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",13,en,Forrest Gump,48.307194,"[{'name': 'Paramount Pictures', 'id': 4}]",1994-07-06,142.0,Released,Forrest Gump,8.2,8147.0,396.118991,8.150042
30533,"[{'id': 35, 'name': 'Comedy'}]",214756,en,Ted 2,42.061481,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",2015-06-25,115.0,Released,Ted 2,6.2,2524.0,260.781182,6.166083
38577,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",291805,en,Now You See Me 2,39.540653,"[{'name': 'Summit Entertainment', 'id': 491}, ...",2016-06-02,129.0,Released,Now You See Me 2,6.7,3362.0,264.922375,6.651163
2200,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",637,it,La vita è bella,39.394970,"[{'name': 'Miramax Films', 'id': 14}, {'name':...",1997-12-20,116.0,Released,Life Is Beautiful,8.3,3643.0,326.978251,8.186649
44790,"[{'id': 35, 'name': 'Comedy'}]",417870,en,Girls Trip,37.964872,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",2017-07-21,122.0,Released,Girls Trip,7.1,393.0,269.550591,6.673151
43633,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",324852,en,Despicable Me 3,36.631519,"[{'name': 'Illumination Entertainment', 'id': ...",2017-06-15,96.0,Released,Despicable Me 3,6.2,2002.0,227.115418,6.157902
42877,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",339846,en,Baywatch,35.637691,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",2017-05-12,116.0,Released,Baywatch,6.1,1829.0,217.389915,6.062380
10292,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",19404,hi,Dilwale Dulhania Le Jayenge,34.457024,"[{'name': 'Yash Raj Films', 'id': 1569}]",1995-10-20,190.0,Released,Dilwale Dulhania Le Jayenge,9.1,661.0,313.558918,8.418468
44728,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",378236,en,The Emoji Movie,33.694599,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...",2017-07-28,86.0,Released,The Emoji Movie,5.8,327.0,195.428674,5.746215
44523,"[{'id': 35, 'name': 'Comedy'}]",345914,en,The House,30.146847,"[{'name': 'New Line Cinema', 'id': 12}, {'name...",2017-06-29,88.0,Released,The House,5.9,91.0,177.866397,5.732012
25422,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",207703,en,Kingsman: The Secret Service,28.224212,[{'name': 'Twentieth Century Fox Film Corporat...,2015-01-29,130.0,Released,Kingsman: The Secret Service,7.6,6069.0,214.504011,7.548981
42867,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",417830,en,Diary of a Wimpy Kid: The Long Haul,28.176992,"[{'name': 'Twentieth Century Fox', 'id': 7392}]",2017-05-19,91.0,Released,Diary of a Wimpy Kid: The Long Haul,6.1,48.0,171.879651,5.743329
23637,"[{'id': 35, 'name': 'Comedy'}]",225886,en,Sex Tape,27.470696,"[{'name': 'Escape Artists', 'id': 1423}, {'nam...",2014-07-17,97.0,Released,Sex Tape,5.2,1733.0,142.847619,5.237414
4742,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",585,en,"Monsters, Inc.",26.419962,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2001-11-01,92.0,Released,"Monsters, Inc.",7.5,6150.0,198.149715,7.452202

### Vote Count and Genre Combined Ranking:

In [26]:
comedy_movies = df[df['genres'].apply(lambda x: 'Comedy' in str(x))]
top_20_comedy_highest_voted = comedy_movies.sort_values(by='vote_count', ascending=False).head(20)
top_20_comedy_highest_voted

,genres,id,original_language,original_title,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count,popularity_vote_avg,weighted_rating
26446,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",293660,en,Deadpool,187.860492,[{'name': 'Twentieth Century Fox Film Corporat...,2016-02-09,108.0,Released,Deadpool,7.4,11444.0,1390.167641,7.375401
350,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",13,en,Forrest Gump,48.307194,"[{'name': 'Paramount Pictures', 'id': 4}]",1994-07-06,142.0,Released,Forrest Gump,8.2,8147.0,396.118991,8.150042
13702,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",14160,en,Up,19.330884,"[{'name': 'Pixar Animation Studios', 'id': 3}]",2009-05-13,96.0,Released,Up,7.8,7048.0,150.780895,7.751415
22048,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",106646,en,The Wolf of Wall Street,16.382422,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",2013-12-25,180.0,Released,The Wolf of Wall Street,7.9,6768.0,129.421134,7.847114
30165,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",150540,en,Inside Out,23.985587,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2015-06-09,94.0,Released,Inside Out,7.9,6737.0,189.486137,7.846876
13724,"[{'id': 35, 'name': 'Comedy'}]",18785,en,The Hangover,23.947351,"[{'name': 'Legendary Pictures', 'id': 923}, {'...",2009-06-05,100.0,Released,The Hangover,7.2,6324.0,172.420927,7.160977
24349,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",177572,en,Big Hero 6,213.849907,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2014-10-24,102.0,Released,Big Hero 6,7.8,6289.0,1668.029275,7.745698
1216,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",105,en,Back to the Future,25.778509,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",1985-07-03,116.0,Released,Back to the Future,8.0,6239.0,206.228072,7.940212
4742,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",585,en,"Monsters, Inc.",26.419962,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2001-11-01,92.0,Released,"Monsters, Inc.",7.5,6150.0,198.149715,7.452202
25422,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",207703,en,Kingsman: The Secret Service,28.224212,[{'name': 'Twentieth Century Fox Film Corporat...,2015-01-29,130.0,Released,Kingsman: The Secret Service,7.6,6069.0,214.504011,7.548981
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,Toy Story,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",1995-10-30,81.0,Released,Toy Story,7.7,5415.0,168.991461,7.640093
18419,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",77338,fr,Intouchables,16.086919,"[{'name': 'Gaumont', 'id': 9}, {'name': 'TF1 F...",2011-11-02,112.0,Released,The Intouchables,8.2,5410.0,131.912736,8.125502
36026,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",269149,en,Zootopia,26.024868,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2016-02-11,108.0,Released,Zootopia,7.7,4961.0,200.391484,7.634784
26448,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,en,Guardians of the Galaxy Vol. 2,185.330992,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2017-04-19,137.0,Released,Guardians of the Galaxy Vol. 2,7.6,4858.0,1408.515539,7.536673
19672,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",82693,en,Silver Linings Playbook,14.488111,"[{'name': 'The Weinstein Company', 'id': 308}]",2012-09-08,122.0,Released,Silver Linings Playbook,7.0,4840.0,101.416777,6.955877
19059,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",72105,en,Ted,19.638605,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",2012-06-29,106.0,Released,Ted,6.3,4811.0,123.723211,6.278423
19021,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",62177,en,Brave,15.876341,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2012-06-21,93.0,Released,Brave,6.7,4760.0,106.371485,6.665034
40579,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",313369,en,La La Land,19.681686,"[{'name': 'Summit Entertainment', 'id': 491}, ...",2016-11-29,128.0,Released,La La Land,7.9,4745.0,155.485319,7.825311
30543,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",211672,en,Minions,547.488298,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",2015-06-17,91.0,Released,Minions,6.4,4729.0,3503.925107,6.374749
21088,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",93456,en,Despicable Me 2,24.823550,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",2013-06-25,98.0,Released,Despicable Me 2,7.0,4729.0,173.764850,6.954876